output_path: "e:/Desktop"
record_interval: 4 # 每段录像的时长，单位秒
segment_retain_time: 600 # 历史分片最大保留时长，单位秒
camera_list:
#  - name: "gate"
#    host: "192.168.1.10"
#    port: 80
#    username: "admin"
#    password: ${ONVIF_PASSWORD}
#    enabled: true
#    record_config:
#      pixel_threshold: 25  # 像素差异阈值
#      motion_ratio_threshold: 0.02  # 像素变化比例阈值（2%）
#      alert_interval: 5  # 告警间隔（秒）
#      frame_skip: 5  # 跳帧间隔
#  - name: "dining room"
#    host: "192.168.1.11"
#    port: 80
#    username: "admin"
#    password: ${ONVIF_PASSWORD}
#    enabled: true
#    record_config:
#      pixel_threshold: 25  # 像素差异阈值
#      motion_ratio_threshold: 0.02  # 像素变化比例阈值（2%）
#      alert_interval: 5  # 告警间隔（秒）
#      frame_skip: 5  # 跳帧间隔
#  - name: "living room"
#    host: "192.168.1.12"
#    port: 80
#    username: "admin"
#    password: ${ONVIF_PASSWORD}
#    enabled: true
#    record_config:
#      pixel_threshold: 25  # 像素差异阈值
#      motion_ratio_threshold: 0.02  # 像素变化比例阈值（2%）
#      alert_interval: 5  # 告警间隔（秒）
#      frame_skip: 5  # 跳帧间隔
#  - name: "kitchen"
#    host: "192.168.1.64"
#    port: 80
#    username: "admin"
#    password: ${ONVIF_PASSWORD}
#    enabled: true
#    record_config:
#      pixel_threshold: 25  # 像素差异阈值
#      motion_ratio_threshold: 0.02  # 像素变化比例阈值（2%）
#      alert_interval: 5  # 告警间隔（秒）
#      frame_skip: 5  # 跳帧间隔
  - name: "room"
    host: "192.168.1.20"
    port: 8899
    username: "admin"
    password: ${ONVIF_PASSWORD}
    enabled: true
    record_config:
      pixel_threshold: 25  # 像素差异阈值
      motion_ratio_threshold: 0.02  # 像素变化比例阈值（2%）
      alert_interval: 1  # 告警间隔（秒）
      frame_skip: 5  # 跳帧间隔
